"""Vehicle type reference data and helper functions."""


VEHICLE_TYPES = {
    # --- Land Vehicles ---
    "cart": {
        "name": "Cart",
        "vehicle_type": "land",
        "hp": 3,  # 1d4 avg
        "ac": 9,
        "cargo_capacity": 4000,
        "movement_rate": 60,
        "cost_gp": 100,
        "crew_min": 0,
        "passengers": 2,
        "description": "Two-wheeled vehicle. Requires 1 draft horse or 2 mules. Double animals for 8,000 cn capacity.",
    },
    "wagon": {
        "name": "Wagon",
        "vehicle_type": "land",
        "hp": 5,  # 2d4 avg
        "ac": 9,
        "cargo_capacity": 15000,
        "movement_rate": 60,
        "cost_gp": 200,
        "crew_min": 0,
        "passengers": 4,
        "description": "Four-wheeled, open vehicle. Requires 2 draft horses or 4 mules. Double animals for 25,000 cn capacity.",
    },

    # --- Seaworthy Vessels ---
    "lifeboat": {
        "name": "Lifeboat",
        "vehicle_type": "seaworthy",
        "hp": 15,
        "ac": 9,
        "cargo_capacity": 15000,
        "movement_rate": 90,
        "cost_gp": 1000,
        "crew_min": 1,
        "passengers": 10,
        "description": "Small boat with folding mast. 20' long. Weighs 5,000 cn when stored aboard a ship.",
    },
    "longship": {
        "name": "Longship",
        "vehicle_type": "seaworthy",
        "hp": 70,
        "ac": 8,
        "cargo_capacity": 40000,
        "movement_rate": 90,
        "cost_gp": 15000,
        "crew_min": 60,
        "passengers": 75,
        "description": "60'-80' narrow ship. Crew serve as oarsmen, sailors, and fighters. Up to 1 catapult.",
    },
    "sailing_ship_large": {
        "name": "Sailing Ship, Large",
        "vehicle_type": "seaworthy",
        "hp": 150,
        "ac": 7,
        "cargo_capacity": 300000,
        "movement_rate": 120,
        "cost_gp": 20000,
        "crew_min": 20,
        "passengers": None,
        "description": "100'-150' vessel with up to three masts. Multiple decks with raised castles.",
    },
    "sailing_ship_small": {
        "name": "Sailing Ship, Small",
        "vehicle_type": "seaworthy",
        "hp": 75,
        "ac": 8,
        "cargo_capacity": 100000,
        "movement_rate": 150,
        "cost_gp": 5000,
        "crew_min": 10,
        "passengers": None,
        "description": "60'-80' vessel with a single mast.",
    },
    "troop_transport_large": {
        "name": "Troop Transport, Large",
        "vehicle_type": "seaworthy",
        "hp": 200,
        "ac": 7,
        "cargo_capacity": 300000,
        "movement_rate": 120,
        "cost_gp": 26600,
        "crew_min": 20,
        "passengers": 100,
        "description": "100'-150' vessel designed to carry troops, mounts, and equipment of war.",
    },
    "troop_transport_small": {
        "name": "Troop Transport, Small",
        "vehicle_type": "seaworthy",
        "hp": 100,
        "ac": 8,
        "cargo_capacity": 100000,
        "movement_rate": 150,
        "cost_gp": 6600,
        "crew_min": 10,
        "passengers": 50,
        "description": "60'-80' vessel designed to carry troops.",
    },
    "warship_large": {
        "name": "Warship, Large",
        "vehicle_type": "seaworthy",
        "hp": 150,
        "ac": 7,
        "cargo_capacity": 300000,
        "movement_rate": 120,
        "cost_gp": 26600,
        "crew_min": 20,
        "passengers": 50,
        "description": "100'-150' vessel designed for mercenaries and war gear. Up to 2 catapults.",
    },
    "warship_small": {
        "name": "Warship, Small",
        "vehicle_type": "seaworthy",
        "hp": 75,
        "ac": 8,
        "cargo_capacity": 100000,
        "movement_rate": 150,
        "cost_gp": 6600,
        "crew_min": 10,
        "passengers": 25,
        "description": "60'-80' vessel designed for mercenaries and war gear. Up to 1 catapult.",
    },

    # --- Unseaworthy Vessels ---
    "boat_river": {
        "name": "Boat, River",
        "vehicle_type": "unseaworthy",
        "hp": 30,
        "ac": 8,
        "cargo_capacity": 30000,
        "movement_rate": 180,
        "cost_gp": 4000,
        "crew_min": 8,
        "passengers": None,
        "description": "20'-30' river barge. Rowed or poled. +1,000 gp for a roof.",
    },
    "boat_sailing": {
        "name": "Boat, Sailing",
        "vehicle_type": "unseaworthy",
        "hp": 30,
        "ac": 8,
        "cargo_capacity": 20000,
        "movement_rate": 120,
        "cost_gp": 2000,
        "crew_min": 1,
        "passengers": None,
        "description": "20'-40' small boat for fishing in lakes or coastal waters.",
    },
    "canoe": {
        "name": "Canoe",
        "vehicle_type": "unseaworthy",
        "hp": 8,
        "ac": 9,
        "cargo_capacity": 6000,
        "movement_rate": 60,
        "cost_gp": 50,
        "crew_min": 1,
        "passengers": None,
        "description": "15' hide/canvas boat. Weighs 500 cn. Can be carried by two people.",
    },
    "galley_large": {
        "name": "Galley, Large",
        "vehicle_type": "unseaworthy",
        "hp": 110,
        "ac": 7,
        "cargo_capacity": 40000,
        "movement_rate": 90,
        "cost_gp": 30000,
        "crew_min": 180,
        "passengers": 50,
        "description": "120'-150' oared warship. Ram can be added. Up to 2 catapults.",
    },
    "galley_small": {
        "name": "Galley, Small",
        "vehicle_type": "unseaworthy",
        "hp": 90,
        "ac": 8,
        "cargo_capacity": 20000,
        "movement_rate": 90,
        "cost_gp": 10000,
        "crew_min": 60,
        "passengers": 20,
        "description": "60'-100' oared vessel. Ram can be added. Up to 2 catapults.",
    },
    "galley_war": {
        "name": "Galley, War",
        "vehicle_type": "unseaworthy",
        "hp": 135,
        "ac": 7,
        "cargo_capacity": 60000,
        "movement_rate": 60,
        "cost_gp": 60000,
        "crew_min": 300,
        "passengers": 75,
        "description": "120'-150' flagship with built-in ram. Two masts, raised towers. Up to 3 catapults.",
    },
    "raft_makeshift": {
        "name": "Raft, Makeshift",
        "vehicle_type": "unseaworthy",
        "hp": 5,
        "ac": 9,
        "cargo_capacity": 5000,
        "movement_rate": 60,
        "cost_gp": 0,
        "crew_min": 1,
        "passengers": None,
        "description": "Logs lashed together. 5 HP per 10' square section. Built in 1-3 days per section.",
    },
    "raft_professional": {
        "name": "Raft, Professional",
        "vehicle_type": "unseaworthy",
        "hp": 5,
        "ac": 9,
        "cargo_capacity": 10000,
        "movement_rate": 60,
        "cost_gp": 100,
        "crew_min": 1,
        "passengers": None,
        "description": "Built raft with raised sides, steering oar, and shelter. Up to 30' x 40'.",
    },
}


def compute_effective_movement(hp_current: int, hp_max: int, base_movement: int) -> int:
    """Hull damage reduces movement proportionally. 10% HP loss = 10% speed reduction."""
    if hp_max <= 0:
        return 0
    ratio = hp_current / hp_max
    return max(0, int(base_movement * ratio))
