"""add_slot_to_character_items

Revision ID: 9fb7e437a9ef
Revises: 7b3882b43b71
Create Date: 2026-02-17 19:50:42.219056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fb7e437a9ef'
down_revision: Union[str, None] = '7b3882b43b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_items', sa.Column('slot', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character_items', 'slot')
    # ### end Alembic commands ###
