"""add_reversible_to_spells

Revision ID: 495d5a9b4f85
Revises: 5f8536ac7a58
Create Date: 2026-02-10 22:18:50.181106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '495d5a9b4f85'
down_revision: Union[str, None] = '5f8536ac7a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spells', sa.Column('reversible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spells', 'reversible')
    # ### end Alembic commands ###
