"""add_admin_role_and_spell_defaults

Revision ID: 5f8536ac7a58
Revises: 
Create Date: 2026-02-08 22:42:06.524302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f8536ac7a58'
down_revision: Union[str, None] = '0000000000000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite
    with op.batch_alter_table('spells', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_spells_is_default'), ['is_default'], unique=False)
        batch_op.create_foreign_key('fk_spells_campaign_id', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_is_admin'), ['is_admin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_is_admin'))
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('spells', schema=None) as batch_op:
        batch_op.drop_constraint('fk_spells_campaign_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_spells_is_default'))
        batch_op.drop_column('is_default')
        batch_op.drop_column('campaign_id')
    # ### end Alembic commands ###
