"""add_movement_rate_to_characters

Revision ID: 67a6b6276b35
Revises: 3b7adfebda06
Create Date: 2026-02-16 11:14:47.168200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67a6b6276b35'
down_revision: Union[str, None] = '3b7adfebda06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('movement_rate', sa.Integer(), nullable=True))
    op.execute("UPDATE characters SET movement_rate = 120 WHERE movement_rate IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'movement_rate')
    # ### end Alembic commands ###
